#!/usr/bin/python

import sys
import getopt
import json
from sense_emu import SenseHat

sense = SenseHat()

p_flag = 0;
r_flag = 0;
y_flag = 0;
u_value = '';

sysarg = sys.argv[1:];

try:
    opts,args = getopt.getopt(sysarg, ':pryu:')
except getopt.GetoptError as err:
            print(err)
            sys.exit(1)
            
for opt, arg in opts:
    if opt in '-p':
        p_flag = 1
    elif opt in '-r':
        r_flag = 1
    elif opt in '-y':
        y_flag = 1
    elif opt in '-u':
        u_value = arg

if p_flag == 1:
    if (u_value == 's') or (u_value == 'S'):
        orient = sense.get_orientation_degrees()
        poz = ("pitch:{pitch}".format(**orient))
        print(json.dumps(poz))
    elif (u_value == 'r') or (u_value == 'R'):
        orient = sense.get_orientation_radians()
        poz = ("pitch:{pitch}".format(**orient))
        print(json.dumps(poz))
if r_flag == 1:
    if (u_value == 's') or (u_value == 'S'):
        orient = sense.get_orientation_degrees()
        poz = ("roll:{roll}".format(**orient))
        print(json.dumps(poz))        
    elif (u_value == 'r') or (u_value == 'R'):
        orient = sense.get_orientation_radians()
        poz = ("r:{roll}".format(**orient))
        print(json.dumps(poz))
if y_flag == 1:
    if (u_value == 's') or (u_value == 'S'):
        orient = sense.get_orientation_degrees()
        poz = ("yaw:{yaw}".format(**orient))
        print(json.dumps(poz))
    elif (u_value == 'r') or (u_value == 'R'):
        orient = sense.get_orientation_radians()
        poz = ("y:{yaw}".format(**orient))
        print(json.dumps(poz))
